version: 2.1

# setup: true # TODO: see how this will combine with other setup workflow
orbs:
  fast-path-filtering: issmirnov/fast-path-filtering@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      # # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      # - fast-path-filtering/filter:
      #     base-revision: main
      #     # mapping: <regexp applied to file list> <build property> <property value>
      #     mapping:
      #       src/commands/.*      commands-modified true
      #     filters: *filters
      #     config-path: .circleci/workflows.yml
      - print-params:
          steps:
            - name: Param printer
              command: |
                echo "Commands were modified and pipeline was triggered"
                echo << pipeline.parameters >>

      - orb-tools/pack:
          filters: *filters
          requires:
            - fast-path-filtering/filter
      - orb-tools/publish:
          orb-name: issmirnov/fast-path-filtering
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - fast-path-filtering/filter
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
